### ISSUE TITLE
Interceptor with a Service

### ISSUE THREAD

**Issue by allanffg** [yulonh/ng2-http-interceptor#1]
Is it possible to have the interceptor class use a service?

I get injection issues because the import for the interceptor specifies a class type and can't resolve the constructor parameters of my Interceptor.

HttpInterceptorModule.withInterceptors([MyHttpInterceptor]),

**Comment by d3dc** [comment]
This has something to do with the Typescript type symbols being erased.

You can use the `@Inject()` decorator to include a symbol in the metadata.

```
constructor(@Inject(MyServiceClass) private myService: MyServiceClass) { ... }
```
