### ISSUE TITLE
[Feature Request] Allow Modifying Request Asynchronously

### ISSUE THREAD

**Issue by d3dc** [yulonh/ng2-http-interceptor#2]
We rely on an Authentication service to return an auth token asynchronously from some API calls and we'd like to attach a (potentially new) token to every request.

Right now, the`HttpInterceptor` interface requires a return type of `Request`

Is it possible to make the `HttpInterceptorBackend` handle waiting on an `Observable` or `Promise`?

**Comment by yulonh** [comment]
You should  get the token from a login action and then store the token in cookie or local storage.
Example:
```typescript
import {RequestMethod, Request, Response} from '@angular/http';
import {Inject} from '@angular/core';
import {HttpInterceptor} from 'angular2-http-interceptor';
import {Router} from '@angular/router';
import {Observable} from 'rxjs';
import {CookieService} from "angular2-cookie/services/cookies.service";

export class AuthInterceptor implements HttpInterceptor {
  constructor(@Inject(Router) private router: Router, @Inject(CookieService) private cookie: CookieService) {
  }

  before(request: Request): Request {
    if (request.method !== RequestMethod.Get && !(request.getBody() instanceof FormData)) {
      request.headers.set('Content-Type', 'application/json;charset=UTF-8');
    }
    let token: string = this.cookie.get('token');
    if (!token && (request.url.indexOf('/login') === -1 || request.url.indexOf('/register')) === -1) {
      this.router.navigate(['/login']);
    }
    token && request.headers.set('token', token);
    return request;
  }

  after(response: Observable<Response>) {
    return response.catch(res => {
      if (res.status === 403) {
        this.router.navigate(['/login']);
      }
      return Observable.throw(res);
    });
  }
}

```

**Comment by d3dc** [comment]
This is what we are doing. I may not have explained my usecase well. I glossed over it with:
> attach a (potentially new) token

How would we handle a token that expires quickly?

Our users will often spend a lot of time inputting data, and the token expires before we make the api request.

**Comment by yulonh** [comment]
I can allow modifying request asynchronously,but you still can not use the http  service in the interceptor,because it will cause a cyclic dependency.

**Comment by perrosen** [comment]
@yulonh Hi mate. The only issue I'm facing with using Observable.throw({}) is that it currently looks down the UI. The normal error handlers aren't called because the error gets captured in HTTP backend instead of returning it to the app.
