### ISSUE TITLE
How can I change the responseData at after function

### ISSUE THREAD

**Issue by zhanxp** [yulonh/ng2-http-interceptor#3]
How can I change the responseData at after function

for example： I want to append a key  at  the response JSON data.

**Comment by yulonh** [comment]
```typescript

  after(response: Observable<Response>) {
    return response.map(res => {
       let data = res.json();
      data.xxx = 'xxx';
      return data;
    });
  }

```

**Comment by Sobiru** [comment]
How can you catch if the result is an error and possibly do something for a particular http status code?

Something like: 

    return res.map(res => {
      // Do something with res
      return res;
    }).catch(
      error => {
        if (error.status)
          if (error.status == 401)
            // do something
        return error;
      });
