### ISSUE TITLE
Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by Sobiru** [yulonh/ng2-http-interceptor#4]
I've followed all the installation steps, but when the app is initialized I get this error: 

`Error encountered resolving symbol values statically. Calling function 'HttpInterceptorModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in path-to-project/app.module.ts, resolving symbol AppModule in path-to-project/app.module.ts`

Even though I'm receiving this everytime app is intialized, the app and the interceptors  work perfectly fine. Any idea what's causing this error?

**Comment by nabeelaxr** [comment]
+ 1

**Comment by nabeelaxr** [comment]
Even I'm facing the same issue

**Comment by yulonh** [comment]
I think this can help you:  https://github.com/angular/angular/issues/11262

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
Facing the same issue here, the interceptor works fine, but the error is just annoying.

**Comment by Arvraepe** [comment]
Having the same issue...

**Comment by es-lab** [comment]
Anyone solved the issue?

**Comment by es-lab** [comment]
@yulonh could you please provide an example how to resolve this error.

**Comment by es-lab** [comment]
@Arvraepe 
@MahmoudEzzatAbdul-Rahman 
@nabeelaxr 
have you found any solution to this?

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
@es-lab I honestly couldn't solve it, so I moved to [ng2-interceptors](https://www.npmjs.com/package/ng2-interceptors)

**Comment by nabeelaxr** [comment]
@es-lab couldn't solve it.

**Comment by es-lab** [comment]
@MahmoudEzzatAbdul-Rahman I tried that already, and I couldn't get what I wanted. 
How do you use it? I couldn't find any specific example to how/when to use it.

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
@es-lab I followed the exact instructions on their page [ng2-interceptors](https://www.npmjs.com/package/ng2-interceptors) and it worked fine, you code your own interceptor service methods and pass them to the interceptor module ..
The little cheat they provide there is very handy also:
`{
    provide: Http,
    useFactory: interceptorFactory,
    deps: [XHRBackend, RequestOptions]
  }` 
you override the HTTP there to the module so that you can use the normal HTTP in your codes and they will instead use the HTTP provided by you

**Comment by es-lab** [comment]
@MahmoudEzzatAbdul-Rahman I've successfully used it for request interception, but when it comes to response interception, there I want to return other data rather than a Response object, maybe a custom json, by doing so, something tries to get the `ok` property but it does not exists, and here I get the error.
Also, could you provide an example on how do you use an interceptor service inside components for showing/hiding loading as in the docs it says you can do this, but no examples given.

**Comment by MahmoudEzzatAbdul-Rahman** [comment]
well, here is my interceptor using `ng2-loading-bar`: I start the loading bar at the intercepted request and complete the loading bar at the interceptor response
`import { Injectable } from '@angular/core';
import { Interceptor, InterceptedRequest, InterceptedResponse } from 'ng2-interceptors';
import { LoadingBarService } from "ng2-loading-bar";
import { NotificationsService } from 'angular2-notifications';
import { RootService } from './root-service.service';

@Injectable()
export class OriginemInterceptor implements Interceptor {
  public interceptBefore(request: InterceptedRequest): InterceptedRequest {
    this.loadingBarService.start();
    return request;
  }

  public interceptAfter(response: InterceptedResponse): InterceptedResponse {
    if (!response.response.ok) {
      let r = response.response;
      let e = r.status + ' ' + r.statusText + '\n' + r.url;
      this.notificationService.html('some html', 'error', { showProgressBar: false }); // Displays a notification containing error info

      this.rootService.setLoadingBarColor('#FF0000'); // Setting loading bar color to red, and reverting to green after a short delay
      setTimeout(() => {
        this.rootService.setLoadingBarColor(this.rootService.loadingBarDefaultColor);
      }, 400);
    }
    this.loadingBarService.complete();
    return response;
  }

  constructor(private loadingBarService: LoadingBarService,
    private notificationService: NotificationsService,
    private rootService: RootService) { }

}`

in the app.module, I give it my intercetpor:
`
export function interceptorFactory(xhrBackend: XHRBackend, requestOptions: RequestOptions, originemInterceptor: OriginemInterceptor) {
  let service = new InterceptorService(xhrBackend, requestOptions);
  // Add interceptors here with service.addInterceptor(interceptor)
  service.addInterceptor(originemInterceptor);
  return service;
}
` 
and the providers: 
`
providers: [LoggerService,
    OriginemInterceptor,
    ...........
     ...........
    {
      provide: Http, // Notice here we're overriding the http
      useFactory: interceptorFactory,
      deps: [XHRBackend, RequestOptions, OriginemInterceptor]
    }]
`
For the different app components, nothing is needed there, they'll use Http normally and our interceptor would work normally.
I don't get exactly what you need to do there, but hope this helps

**Comment by yulonh** [comment]
@Sobiru @nabeelaxr @MahmoudEzzatAbdul-Rahman @es-lab
