### ISSUE TITLE
Getting Error While Build With Angular CLI

### ISSUE THREAD

**Issue by nitin-soni** [yulonh/ng2-http-interceptor#5]
ERROR in Error encountered resolving symbol values statically. Calling function 'HttpInterceptorModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in /app/app.module.ts, resolving symbol AppModule in /app/app.module.ts

**Comment by yulonh** [comment]
@nitin-soni please update to 1.2.9 version.

**Comment by nitin-soni** [comment]
Its already at same. Here is my dependencies

 "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-http-interceptor": "^1.2.9",
    "core-js": "^2.4.1",
    "ng2-meta": "^2.0.3",
    "rxjs": "^5.0.1",
    "systemjs": "^0.20.5",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },

**Comment by yulonh** [comment]
@nitin-soni can you upload you project source?

**Comment by nitin-soni** [comment]
I can not upload the complete code. But will share you code so you can reproduce.

**Comment by Arvraepe** [comment]
I had the same issue, but the newest version (1.2.9) fixed the issue. Try throwing away your node_modules folder and do another npm install (just for sanity's sake)

**Comment by Arvraepe** [comment]
Using the interceptors now and this error is coming up frequently but also randomly... some rebuilds later the issue is fixed... it's really weird and no stack trace that can point to the issue

**Comment by yulonh** [comment]
Can you make a demo to show this error? @Arvraepe

**Comment by Arvraepe** [comment]
hmmm it's hard to make a demo, not in the position to share code, and the error is too random. Currently I'm having the issue while I didn't have it last time I ran (last wednesday)

**Comment by yulonh** [comment]
I think upgrade typescript to 2.2.0 can fix this issue, but I am not sure. @Arvraepe

**Comment by Arvraepe** [comment]
I'll try doing that, its funny to see that it's only on the first run... when I change something in the code and angular-cli picks up the change, the error is gone

**Comment by yulonh** [comment]
Please upgrade to the newest version (2.0.0) to fix this issue.
