### ISSUE TITLE
When is before and after called?

### ISSUE THREAD

**Issue by Arvraepe** [yulonh/ng2-http-interceptor#8]
In my application I do two requests when the application loads (for example getting the internalization file).

When I log the interceptor calls of before (logs "before sending") and after (logs "on response") I get the following output:

on response
before sending
on response
before sending

It's weird to me that first the "after" is called and then the "before"

Any thoughts?

**Comment by samw2k00** [comment]
I  had exactly the same issue,
the response is being call before the request and with the response since it being call before, there is nothing in the res: Observable<Response>
I think something must be wrong with the way After is being called

**Comment by Arvraepe** [comment]
well, I implemented the exact feature and then it was working just fine... I think this problem occured when you just log in the function. The function is called before the request is send, because you need to attach a subscription to the result... thats why the log is called first... if you subscribe on the observable response, everything worked out just fine here

**Comment by samw2k00** [comment]
Hi @Arvraepe  

I implemented a proper subscribe and observable call.  I made a request to my own back end but i can see the response is being logged first.

**Comment by yulonh** [comment]
@Arvraepe @samw2k00 You should read the source code and learn about rxjs. Thanks.
