### ISSUE TITLE
Intercept body in before ?

### ISSUE THREAD

**Issue by fbrun** [yulonh/ng2-http-interceptor#9]
is it possible to intercept body value in "before" function ?
I need to encode the value when it's an object type, and then stringify it (my content-type request header need to be x-www-form-urlencoded)
I see in the request there is a getBody() function, but no setter.

Thanks for your help

**Comment by yulonh** [comment]
You can override the getBody() function. 
```typescript
  before(req: Request) {
    let body = req.getBody();
    body = doSomethingWithBody(body);
    req.getBody = ()=>body; 
    return req;
  }


```

**Comment by fbrun** [comment]
Great, thanks. I'll do it like that.
